import { createHash } from 'node:crypto'
import { realpathSync } from 'node:fs'
import { createServer } from 'node:http'
import { MemoryCompositionRunner } from 'dsh-mnemon/testing'
import * as runtimePlugin from 'dsh-mnemon-source-runtime'
import * as spacesPlugin from 'dsh-mnemon-source-memory-spaces'
import * as strategyPlugin from 'dsh-mnemon-strategy-default-three-tier'

/**
 * Working memory that an earlier, failed archive attempt already copied into
 * its Memory Space word for word (issue #339).
 */
export const archiveCopiesEntries = [
  { content: 'Issue 339 synthetic rule: release candidates run the full verify locally, then the packed-plugin checks, before a maintainer approves the release pull request.', importance: 'normal' },
  { content: 'Issue 339 synthetic rule: database migrations ship with a rollback script and a dry run against the staging snapshot; never edit an applied migration.', importance: 'normal' },
  { content: 'Issue 339 synthetic rule: dependency upgrades land one package family at a time, each with its changelog read and the lockfile regenerated by the pinned pnpm.', importance: 'normal' },
]

/** The working-memory entry to add next; it does not fit, so the Host archives the others first. */
export const archiveCopiesPending = 'Issue 339 synthetic rule: on-call maintainers record every production decision in the project documents within the same day, with the evidence they relied on and the follow-up owner.'

/** MEMORY.md fits the seeded entries but not the next one. */
export const archiveCopiesLimitBytes = 640

/** A deterministic vector per text, as an OpenAI-compatible embedding service returns. */
function vector(text) {
  const values = []
  let seed = createHash('sha256').update(text).digest()
  for (let index = 0; index < 256; index++) {
    if (index > 0 && index % 32 === 0) seed = createHash('sha256').update(seed).digest()
    values.push((seed[index % 32] - 128) / 128)
  }
  return values
}

/**
 * An OpenAI-compatible embedding endpoint that answers every embedding request
 * after `delayMs`: slower than the Mnemon CLI's default 10 s timeout, as a
 * remote service under load can be. Model listing answers at once.
 */
export function slowEmbeddingServer({ delayMs, report }) {
  let requests = 0
  return createServer(async (request, response) => {
    let input = ''
    for await (const chunk of request) input += chunk
    if ((request.url ?? '').endsWith('/models')) {
      response.writeHead(200, { 'content-type': 'application/json' })
      response.end(JSON.stringify({ object: 'list', data: [{ id: 'fixture-embed', object: 'model' }] }))
      return
    }
    requests += 1
    report({ event: 'embedding-request', request: requests, delayMs })
    await new Promise(resolve => setTimeout(resolve, delayMs))
    let texts = []
    try {
      const body = JSON.parse(input)
      texts = Array.isArray(body.input) ? body.input : [body.input ?? body.prompt ?? '']
    } catch {}
    if (response.destroyed) return
    response.writeHead(200, { 'content-type': 'application/json' })
    response.end(JSON.stringify({ object: 'list', model: 'fixture-embed', data: texts.map((text, index) => ({ object: 'embedding', index, embedding: vector(String(text)) })), usage: { prompt_tokens: 1, total_tokens: 1 } }))
  })
}

/**
 * Seed the working memory and a Mnemon Native Memory Space that already holds
 * an exact copy of every entry, through the Sources' own management operations
 * and before the Host starts. The space is written without embeddings.
 */
export async function seedArchiveCopies({ dataDir, workspace }) {
  const runner = new MemoryCompositionRunner()
  try {
    await runner.mount(strategyPlugin, { instanceId: 'archive-strategy' })
    await runner.mount(runtimePlugin, { instanceId: 'runtime', config: { dataDir, userDataDir: dataDir } })
    await runner.mount(spacesPlugin, { instanceId: 'memory-spaces', config: {
      dataDir, timeoutMs: 20_000,
      providers: [{ use: 'dsh-mnemon-provider-mnemon-native', instanceId: 'mnemon-native' }],
    } })
    const scope = { storage: 'global', workspaceId: realpathSync(workspace) }
    const runtime = await runner.managementClient('source:runtime', scope)
    for (const entry of archiveCopiesEntries) await runtime.mutate('mutate', { action: 'add', target: 'memory', ...entry }, { confirmed: true })
    const spaces = await runner.managementClient('source:memory-spaces', scope)
    const body = (await spaces.mutate('body-create', { name: 'Project notes', description: 'Release, migration and dependency rules of the synthetic project.', active: true, providerId: 'mnemon-native', connection: {} }, { confirmed: true })).value
    await spaces.mutate('remember-many', { requests: archiveCopiesEntries.map(entry => ({ content: entry.content, category: 'context', importance: 3, source: 'agent', memoryBodyId: body.id })) }, { confirmed: true })
    return body.id
  } finally {
    await runner.dispose()
  }
}
